chat/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('delete<int:pk>/', views.delete, name='delete'),
    path('edit<int:pk>/', views.edit, name='edit'),
    path('new_room<str:username>/', views.new_room, name='new_room'),
    path('chat<str:name>/', views.private_chat, name='private_chat'),
]

webpage/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('register/', include(('register.urls','register'), namespace='register')),
    path('profile/', include(('profile.urls','profile'), namespace='profile')),
    path('chat/', include(('chat.urls','chat'), namespace='chat')),
    path('', include(('main.urls','main'), namespace='main')),
    path('admin/', admin.site.urls),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# Create your models here.

class Room(models.Model):
    name = models.CharField(max_length=200,null=True)
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Message(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    description = models.TextField(null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True)
    
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description

chat/forms.py
from django.forms import ModelForm
from django.http import request

from .models import Message, Room
from django import forms
from django.contrib.auth.models import User
from django.forms import CheckboxSelectMultiple

class MessageForm(ModelForm):
    
    class Meta:
        model = Message
        fields = ['description']

class RoomForm(forms.ModelForm):

    def __init__(self, admin, *args, **kwargs):
        self.admin = admin
        super(RoomForm, self).__init__(*args, **kwargs)
        self.fields['members'].queryset = User.objects.exclude(username=admin.username)

    members = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        widget=CheckboxSelectMultiple
    )

    class Meta:
        model = Room
        fields = ['name', 'members']

chat/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import MessageForm, RoomForm
from .models import Message, Room
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    messages = Message.objects.all()
    rooms = Room.objects.filter(members__username=request.user)

    User = get_user_model()
    users = User.objects.all()
        
    context = {'messages':messages,
               'users':users,
               'rooms':rooms}
    return render(request, 'chat/home.html', context)

@login_required(login_url='login')
def delete(request, pk):
    message = Message.objects.get(id=pk)

    if request.method == "POST":
        message.delete()
        return redirect('chat:home')

    context = {}
    return render(request, 'chat/delete.html', context)

def edit(request, pk):
    message = Message.objects.get(id=pk)
    form = MessageForm(instance=message)

    if request.method == "POST":
        form = MessageForm(request.POST, instance=message)
        if form.is_valid():
            message.save()
            return redirect('chat:home')

    context = {'form':form}
    return render(request, 'chat/edit.html', context)

def new_room(request, username):
    user = User.objects.get(username=username)
    form = RoomForm(request.user)
    room = Room()

    if request.method == "POST":
        form = RoomForm(request.POST)
        print(form)
        if form.is_valid():
            room = form.save(commit=False)
            room.save()
            for member in form.cleaned_data['members']:
                room.members.add(member)
            room.members.add(request.user)
            return redirect('chat:home')
    
    context = {'user':user,
               'form':form,}
    return render(request, 'chat/new_room.html', context)

def private_chat(request, name):
    room = Room.objects.get(name=name)
    message = Message.objects.filter(room=room)

    form = MessageForm()
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid() and request.POST.get('description'):
            message = form.save(commit=False)
            message.author = request.user
            message.room = room
            message.save()
            return redirect('chat:private_chat', name=room.name)
    
    
    rooms = Room.objects.filter(members__username=request.user)
    messages = Message.objects.filter(room=room)
    context = {'messages':messages,
               'form':form,
               'rooms':rooms}
    print(message)
    return render(request, 'chat/private_chat.html', context)

chat/templates/chat/contacts.html
{% extends 'navbar.html' %}

{% block content %}

<h2>Test</h2>

{% endblock %}

chat/templates/chat/delete.html
<form action="" method="POST">
    {% csrf_token %}
    <h3>Are you sure to delete message?</h3>
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Delete">
</form>

chat/templates/chat/home.html
{% extends 'main.html' %}

{% block section %}

{% endblock %}

{% block nav %}
<a href="{% url 'chat:new_room' user.username %}">New Conversation</a>
<div class="rooms_list">
    <p>List of conversations:</p>
    {% for room in rooms%}
    <div class="room_name">
        <a href="{% url 'chat:private_chat' room.name %}">{{room.name}}</a>
    </div>
    {% endfor %}
</div>

{% endblock %}

chat/templates/chat/new_room.html
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Create">
</form>

chat/templates/chat/private_chat.html
{% extends './home.html' %}

{% block section %}

{% for message in messages%}
<div class="message_box">
    <div class="{% if message.author == request.user %}message_author{% else %}message{% endif %}">
        <h6>--{{message.author}}</h6>
        <h6>--{{message.created}}</h6>
        <h2>{{message.description}}</h2>
        <a href="{% url 'chat:delete' message.id %}">Delete</a>
        <a href="{% url 'chat:edit' message.id %}">Edit</a>
    </div>
</div>
{% endfor %}

<div class="message_sent">
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Sent">
    </form>
</div>


{% endblock %}