chat/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('delete<int:pk>/', views.delete, name='delete'),
    path('edit<int:pk>/', views.edit, name='edit'),
    path('new_room<str:username>/', views.new_room, name='new_room'),
    path('chat<str:name>/', views.private_chat, name='private_chat'),
]

profile/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/edit', views.edit, name='edit'),
]



urlpatterns += staticfiles_urlpatterns()

webpage/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('register/', include(('register.urls','register'), namespace='register')),
    path('profile/', include(('profile.urls','profile'), namespace='profile')),
    path('chat/', include(('chat.urls','chat'), namespace='chat')),
    path('', include(('main.urls','main'), namespace='main')),
    path('admin/', admin.site.urls),
]

profile/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User

class EditForm(ModelForm):
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

profile/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User
from .forms import EditForm

# Create your views here.

def profile(request, username):
    user = User.objects.get(username=username)
    user_url = f"/static/profile/media/{user.username}.jpg"

    context = {'user':user,
               'user_url':user_url}

    return render(request, 'profile/home.html', context)

def edit(request, username):
    user = User.objects.get(username=username)
    form = EditForm(instance=user)

    if request.method == "POST":
        form = EditForm(request.POST, instance=user)
        if form.is_valid():
            user.save()
            return redirect('profile:profile', username=user.username)

    context = {'user':user,
               'form':form}
    
    return render(request, 'profile/edit.html', context)

profile/templates/profile/edit.html
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Edit">
</form>

profile/templates/profile/home.html
{% extends 'main.html' %}

{% block section %}

<div>
    <h2>{{user.username}}</h2>
</div>

<div class="profile_photo">
    <img src={{user_url}} alt="profile_photo">
</div>

{% if user == request.user %}
<div>
    <a href="{% url 'profile:edit' user.username %}">Edit profile</a>
</div>
{% endif %}

<br>
<p>First name: {{user.first_name}}</p>
<p>Last name: {{user.last_name}}</p>
<p>Email: {{user.email}}</p>

{% endblock %}