chat/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('delete<int:pk>/', views.delete, name='delete'),
    path('edit<int:pk>/', views.edit, name='edit'),
    path('new_room<str:username>/', views.new_room, name='new_room'),
    path('chat<str:name>/', views.private_chat, name='private_chat'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

profile/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/edit', views.edit, name='edit'),
]



urlpatterns += staticfiles_urlpatterns()

register/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('singup/', views.singUpUser, name='singup'),
    path('logout/', views.logoutUser, name='logout'),
]

webpage/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('register/', include(('register.urls','register'), namespace='register')),
    path('profile/', include(('profile.urls','profile'), namespace='profile')),
    path('chat/', include(('chat.urls','chat'), namespace='chat')),
    path('', include(('main.urls','main'), namespace='main')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.models import User


def home(request):
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'main/home.html', context)

templates/footer.html
<p>Author: Jakub Stachowicz</p>

templates/header.html
{% if request.user.is_authenticated %}
    <a href="{% url 'register:logout' %}">Logout</a>
    <a href="{% url 'profile:profile' user.get_username %}">Profile</a>
{% else %}
    <a href="{% url 'register:login' %}">Login</a>
    <a href="{% url 'register:singup' %}">Sing up</a>
{% endif %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JStachowicz</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>MESSENGER</h1>

    <header>
        <div id="main_head">
            <a href="{% url 'main:home' %}">Main</a>
        </div>
        <div id="logging_head">
            {% include 'header.html' %}
        </div>
        <br><hr>
    </header>

    <nav>
        {% block nav %}

        {% endblock %}
    </nav>

    <section>
        {% block section %}

        {% endblock %}
    </section>

    <footer>
        {% include 'footer.html' %}
    </footer>
</body>
</html>