chat/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('delete<int:pk>/', views.delete, name='delete'),
    path('edit<int:pk>/', views.edit, name='edit'),
    path('new_room<str:username>/', views.new_room, name='new_room'),
    path('chat<str:name>/', views.private_chat, name='private_chat'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

profile/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/edit', views.edit, name='edit'),
]



urlpatterns += staticfiles_urlpatterns()

webpage/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('register/', include(('register.urls','register'), namespace='register')),
    path('profile/', include(('profile.urls','profile'), namespace='profile')),
    path('chat/', include(('chat.urls','chat'), namespace='chat')),
    path('', include(('main.urls','main'), namespace='main')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.models import User


def home(request):
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'main/home.html', context)

main/templates/main/home.html
{% extends 'main.html' %}

{% block section %}

{% if user.is_authenticated %}
<a href="{% url 'chat:home' %}"><h1>MESSENGER</h1></a>
{% endif %}

{% endblock %}

{% block nav %}

<div class="contact_list">
    {% for user in users %}
    <div class="contact_user">
        <a href="{% url 'profile:profile' user.username %}">{{user}}</a>
    </div>
    {% endfor %}
</div>

{% endblock %}